version: '3'

services:

  postgresql:
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=Rahasia
      - POSTGRES_DB=toko_mandiri
    networks:
      - app-network
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    image: postgres

  todo-app:
    container_name: todo-app
    environment:
      - HOST_DB=postgresql
      - PORT_DB=5432
      - APP_PORT=8090
      - DB_NAME=toko_mandiri
      - USERNAME_DB=postgres
      - PASSWORD_DB=Rahasia
    ports:
      - "8085:8090"
    build: .
    networks:
      - app-network

volumes:
  postgres-data:
networks:
  app-network:
    driver: bridge


